# Generated by Django 3.2 on 2021-04-13 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unchained', '0002_auto_20210413_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdiscontentreport',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customerdiscontentreport', to='unchained.servicecategory'),
        ),
        migrations.AddField(
            model_name='prospectdealreport',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospectdealreport', to='unchained.servicecategory'),
        ),
        migrations.AddField(
            model_name='technicalissuereport',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technicalissuereport', to='unchained.servicecategory'),
        ),
        migrations.AddField(
            model_name='useraccountcontrolreport',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='useraccountcontrolreport', to='unchained.servicecategory'),
        ),
        migrations.AddField(
            model_name='useraccountinforeport',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='useraccountinforeport', to='unchained.servicecategory'),
        ),
        migrations.AlterField(
            model_name='servicerange',
            name='category',
            field=models.ForeignKey(default='Тарифный план', on_delete=django.db.models.deletion.PROTECT, related_name='servicerange', to='unchained.servicecategory'),
            preserve_default=False,
        ),
    ]
