# Generated by Django 3.2 on 2021-04-08 15:09

from django.db import migrations, models
import django.db.models.deletion
import unchained.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCategory',
            fields=[
                ('code', models.PositiveIntegerField(default=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On leave', 'On Leave'), ('Quited', 'Quited')], default='Active', max_length=8)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('dial_extension', models.IntegerField(default=1)),
                ('token', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRange',
            fields=[
                ('code', models.PositiveIntegerField(default=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicecategory', to='unchained.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('name', models.CharField(primary_key=True, choices=[('Тарифный план', 'Tariff'), ('Голосовая связь', 'Voice Service'), ('SMS/MMS', 'Sms Mms Service'), ('Интернет', 'Internet Providing'), ('Платежи/переводы', 'Pay Banking Service'), ('Подписки на контент', 'Extra Subscription Service'), ('Сервисы самообслуживания', 'Self Service Providing')], default='Tariff', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('code', models.PositiveIntegerField(default=101, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('base_category_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='unchained.basecategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountInfoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_phone', models.CharField(max_length=20)),
                ('caller_customer_type', models.CharField(choices=[('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10)),
                ('caller_contract_region', models.CharField(blank=True, max_length=30)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('extended_notes', models.TextField(blank=True)),
                ('report_id', models.PositiveIntegerField(default=unchained.models.CallHandlingReport.set_unique_child_id)),
                ('base_category_code', models.ForeignKey(default=200, on_delete=django.db.models.deletion.PROTECT, related_name='useraccountinforeport', to='unchained.basecategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='useraccountinforeport', to='unchained.employee')),
                ('service_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='useraccountinforeport', to='unchained.servicerange')),
                ('subcategory_code', models.ForeignKey(default=201, on_delete=django.db.models.deletion.PROTECT, related_name='useraccountinforeport', to='unchained.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccountControlReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_phone', models.CharField(max_length=20)),
                ('caller_customer_type', models.CharField(choices=[('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10)),
                ('caller_contract_region', models.CharField(blank=True, max_length=30)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('extended_notes', models.TextField(blank=True)),
                ('report_id', models.PositiveIntegerField(default=unchained.models.CallHandlingReport.set_unique_child_id)),
                ('base_category_code', models.ForeignKey(default=200, on_delete=django.db.models.deletion.PROTECT, related_name='useraccountcontrolreport', to='unchained.basecategory')),
                ('disabled_service_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='useraccountcontrolreport_off', to='unchained.servicerange')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='useraccountcontrolreport', to='unchained.employee')),
                ('enabled_service_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='useraccountcontrolreport_on', to='unchained.servicerange')),
                ('subcategory_code', models.ForeignKey(default=201, on_delete=django.db.models.deletion.PROTECT, related_name='useraccountcontrolreport', to='unchained.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalIssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_phone', models.CharField(max_length=20)),
                ('caller_customer_type', models.CharField(choices=[('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10)),
                ('caller_contract_region', models.CharField(blank=True, max_length=30)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('extended_notes', models.TextField(blank=True)),
                ('report_id', models.PositiveIntegerField(default=unchained.models.CallHandlingReport.set_unique_child_id)),
                ('user_equipment', models.CharField(max_length=80)),
                ('start_timestamp', models.DateTimeField()),
                ('region', models.CharField(blank=True, max_length=30)),
                ('area', models.CharField(max_length=50)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('building', models.CharField(blank=True, max_length=10)),
                ('main_issue_effect', models.CharField(max_length=80)),
                ('base_category_code', models.ForeignKey(default=200, on_delete=django.db.models.deletion.PROTECT, related_name='technicalissuereport', to='unchained.basecategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technicalissuereport', to='unchained.employee')),
                ('service_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technicalissuereport', to='unchained.servicerange')),
                ('subcategory_code', models.ForeignKey(default=201, on_delete=django.db.models.deletion.PROTECT, related_name='technicalissuereport', to='unchained.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealTimeRecognitionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip_address', models.CharField(max_length=50)),
                ('websocket_connection_address', models.CharField(max_length=50)),
                ('stasis_instance_name', models.CharField(max_length=10)),
                ('stasis_pid', models.PositiveIntegerField(default=1)),
                ('monitor_file_name', models.CharField(max_length=80)),
                ('websocket_pid', models.PositiveIntegerField(default=1)),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtimerecognitioncontrol', to='unchained.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProspectDealReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_phone', models.CharField(max_length=20)),
                ('caller_customer_type', models.CharField(choices=[('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10)),
                ('caller_contract_region', models.CharField(blank=True, max_length=30)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('extended_notes', models.TextField(blank=True)),
                ('report_id', models.PositiveIntegerField(default=unchained.models.CallHandlingReport.set_unique_child_id)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('contact_time_period', models.DateTimeField()),
                ('base_category_code', models.ForeignKey(default=200, on_delete=django.db.models.deletion.PROTECT, related_name='prospectdealreport', to='unchained.basecategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospectdealreport', to='unchained.employee')),
                ('service_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospectdealreport', to='unchained.servicerange')),
                ('subcategory_code', models.ForeignKey(default=201, on_delete=django.db.models.deletion.PROTECT, related_name='prospectdealreport', to='unchained.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDiscontentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_phone', models.CharField(max_length=20)),
                ('caller_customer_type', models.CharField(choices=[('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10)),
                ('caller_contract_region', models.CharField(blank=True, max_length=30)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('extended_notes', models.TextField(blank=True)),
                ('report_id', models.PositiveIntegerField(default=unchained.models.CallHandlingReport.set_unique_child_id)),
                ('involved_employee', models.CharField(blank=True, max_length=60)),
                ('business_unit', models.CharField(blank=True, choices=[('Own retail store', 'Own Retail Store'), ('Partner retail store', 'Partner Retail Store'), ('Contact center', 'Contact Center')], default='Own retail store', max_length=20)),
                ('store_address', models.CharField(blank=True, max_length=100)),
                ('refunding_amount', models.FloatField(blank=True)),
                ('base_category_code', models.ForeignKey(default=200, on_delete=django.db.models.deletion.PROTECT, related_name='customerdiscontentreport', to='unchained.basecategory')),
                ('case_service_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customerdiscontentreport', to='unchained.servicerange')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customerdiscontentreport', to='unchained.employee')),
                ('subcategory_code', models.ForeignKey(default=201, on_delete=django.db.models.deletion.PROTECT, related_name='customerdiscontentreport', to='unchained.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactCancelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_phone', models.CharField(max_length=20)),
                ('caller_customer_type', models.CharField(choices=[('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10)),
                ('caller_contract_region', models.CharField(blank=True, max_length=30)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('extended_notes', models.TextField(blank=True)),
                ('report_id', models.PositiveIntegerField(default=unchained.models.CallHandlingReport.set_unique_child_id)),
                ('cancel_ground', models.CharField(choices=[('Wrong / unknown basic security requisites', 'Wrong Unknown Basic Requisites'), ('Wrong / unknown caller password', 'Wrong Unknown Caller Password')], default='Wrong / unknown basic security requisites', max_length=41)),
                ('base_category_code', models.ForeignKey(default=200, on_delete=django.db.models.deletion.PROTECT, related_name='contactcancelreport', to='unchained.basecategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactcancelreport', to='unchained.employee')),
                ('subcategory_code', models.ForeignKey(default=201, on_delete=django.db.models.deletion.PROTECT, related_name='contactcancelreport', to='unchained.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommonInfoProvisionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_phone', models.CharField(max_length=20)),
                ('caller_customer_type', models.CharField(choices=[('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10)),
                ('caller_contract_region', models.CharField(blank=True, max_length=30)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('extended_notes', models.TextField(blank=True)),
                ('report_id', models.PositiveIntegerField(default=unchained.models.CallHandlingReport.set_unique_child_id)),
                ('base_category_code', models.ForeignKey(default=200, on_delete=django.db.models.deletion.PROTECT, related_name='commoninfoprovisionreport', to='unchained.basecategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commoninfoprovisionreport', to='unchained.employee')),
                ('service_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commoninfoprovisionreport', to='unchained.servicerange')),
                ('subcategory_code', models.ForeignKey(default=201, on_delete=django.db.models.deletion.PROTECT, related_name='commoninfoprovisionreport', to='unchained.subcategory')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicecategory', to='unchained.servicecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
