# Generated by Django 3.2 on 2021-04-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unchained', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerange',
            name='service_category',
        ),
        migrations.AddField(
            model_name='servicerange',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicerange', to='unchained.servicecategory'),
        ),
        migrations.AlterField(
            model_name='commoninfoprovisionreport',
            name='caller_customer_type',
            field=models.CharField(choices=[('NONE', 'None'), ('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10),
        ),
        migrations.AlterField(
            model_name='commoninfoprovisionreport',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commoninfoprovisionreport', to='unchained.servicecategory'),
        ),
        migrations.AlterField(
            model_name='contactcancelreport',
            name='caller_customer_type',
            field=models.CharField(choices=[('NONE', 'None'), ('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10),
        ),
        migrations.AlterField(
            model_name='customerdiscontentreport',
            name='caller_customer_type',
            field=models.CharField(choices=[('NONE', 'None'), ('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10),
        ),
        migrations.AlterField(
            model_name='prospectdealreport',
            name='caller_customer_type',
            field=models.CharField(choices=[('NONE', 'None'), ('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(choices=[('Тарифный план', 'Tariff'), ('Голосовая связь', 'Voice Service'), ('SMS/MMS', 'Sms Mms Service'), ('Интернет', 'Internet Providing'), ('Платежи/переводы', 'Pay Banking Service'), ('Подписки на контент', 'Extra Subscription Service'), ('Сервисы самообслуживания', 'Self Service Providing')], default='Тарифный план', max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technicalissuereport',
            name='caller_customer_type',
            field=models.CharField(choices=[('NONE', 'None'), ('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccountcontrolreport',
            name='caller_customer_type',
            field=models.CharField(choices=[('NONE', 'None'), ('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccountinforeport',
            name='caller_customer_type',
            field=models.CharField(choices=[('NONE', 'None'), ('IND', 'Individual'), ('CORP <B2B>', 'Corporate B2B'), ('CORP <B2G>', 'Corporate B2G')], default='IND', max_length=10),
        ),
    ]
